### ISSUE TITLE
Move this into the rust-syndication organization?

### ISSUE THREAD

**Issue by porglezomp** [rust-syndication/syndication#9]
I was doing RSS/Atom parsing again recently, and thought about this crate. Do you think it would benefit from moving into the @rust-syndication organization?

**Comment by tomshen** [comment]
That sounds pretty reasonable to me, though without #5 I don't think this crate does anything incredibly useful.

**Comment by porglezomp** [comment]
If this will have a future somewhere I'll put the work in to finish that up. I think having some input from them will also help some.

**Comment by Riduidel** [comment]
Has there been any progress on that subject ? It's 2019, this crate seems to be dead, and since rss and atom crates have moved, it is now quite unusable.

**Comment by porglezomp** [comment]
The @rust-syndication people are @frewsxcv, @DCjanus, @jameshurst, and @PhnxRbrn. To all of you: is this (with some improved version of the API in #5 completed) a useful addition to the rust-syndication org? If you'd be willing to accept it and give brief comments on the common feed format, I'll finish up the common format work.

I personally still find it useful to have a fire-and-forget "please parse this feed for me" in my own tools, but I don't know if it's worth the maintenance burden to you all.

**Comment by frewsxcv** [comment]
hey all, i'm happy to move this repo into the rust-syndication organization, but don't have much time to directly contribute to developing it. if this is desired, just submit a request to transfer the repo to the org and i'll accept it 👋

**Comment by tomshen** [comment]
I think it makes sense to move it into the org, since I don't plan on working on this repository in the near future.

@frewsxcv in order for me to initiate the transfer, I need [permissions to create new repositories](https://help.github.com/articles/transferring-a-repository/#repository-transfers-and-organizations) in rust-syndication. If you're willing to grant me those permissions, I'll transfer the repo, and I don't mind if you revoke those permissions immediately after I do so.

**Comment by tomshen** [comment]
Transferred! Thanks for the help @frewsxcv
